"""agregar rol

Revision ID: fc69b272cbe4
Revises: 293f74312684
Create Date: 2026-04-14 00:28:51.408127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc69b272cbe4'
down_revision = '293f74312684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_description'))
        batch_op.drop_index(batch_op.f('ix_rooms_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_name'))

    op.drop_table('rooms')
    with op.batch_alter_table('etiqueta', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['slug'])

    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=200), nullable=False))
        batch_op.drop_column('Titulo')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=True))
        batch_op.alter_column('passwordUser',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('passwordUser',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('rol')

    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Titulo', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('titulo')

    with op.batch_alter_table('etiqueta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('slug',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.create_table('rooms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_description'), ['description'], unique=False)

    # ### end Alembic commands ###
